Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -50,11 +50,12 @@ jobs:
         run: |
           for target in ${{ github.event.client_payload.targets || inputs.targets }}; do
             mkdir -vp repo && rm -vrf repo/* 
-            mkdir -vp "public/${target#*:}/${target%:*}"
-            echo "Repo:'${target%:*}'\nBranch:'${target#*:}'"
-            git clone --single-branch --branch ${target%:*} ${target#*:} repo || ( echo "Failed to checkout ${target}"; continue )
+            mkdir -vp "public/${target%:*}/${target#*:}"
+            echo "Repo:'${target%:*}'"
+            echo "Branch:'${target#*:}'"
+            git clone --single-branch --branch ${target#*:} ${target%:*} repo || ( echo "Failed to checkout ${target}"; continue )
             (cd repo && pip install -r requirements.txt)
-            (cd repo && mkdocs build --dirty --quiet --site-dir ../public/${target#*:}/${target%:*})
+            (cd repo && mkdocs build --dirty --quiet --site-dir ../public/${target%:*}/${target#*:})
           done
           chmod -c -R +rX public/ | while read line; do
             echo "::info title=Invalid file permissions automatically fixed::$line"
@@ -87,7 +88,7 @@ jobs:
       - name: Print message
         run: |
           for target in ${{ github.event.client_payload.targets || inputs.targets }}; do                
-            echo "::notice title=Deployment Sucessful::Branch '${target}' deployed to ${DEPLOY_URL}/${target#*:}/${target%:*}"
+            echo "::notice title=Deployment Sucessful::Branch '${target}' deployed to ${DEPLOY_URL}/${target%:*}/${target#*:}"
           done
       # - name: Post Cmment to PR
       #   run: |
