Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -49,8 +49,8 @@ jobs:
       - name: Create dev sub-deployments
         run: |
           for target in ${{ github.event.client_payload.targets || inputs.targets }}; do
-            echo "::group::Building for Repo:'${target%:*}' Branch:'${target#*:}"
-            echo "::group::Setting Up Directorys"
+            echo "Building for Repo:'${target%:*}' Branch:'${target#*:}"
+            echo "::group::Setting Up Directories"
             rm -rf repo && mkdir -vp repo
             mkdir -vp "public/${target%:*}/${target#*:}"        
             echo "git clone --single-branch --branch ${target#*:} https://github.com/${target%:*} repo"
@@ -58,13 +58,12 @@ jobs:
             echo ::endgroup::
             echo "::group::Installing Dependencies"
             ls -latr repo
-            (cd repo && pip install -r requirements.txt)
+            (cd repo && pip install -r requirements.txt) ||  echo "Failed to install dependencies for ${target}";continue
             echo ::endgroup::
             echo "::group::Building"
-            (cd repo && mkdocs build --dirty --site-dir ../public/${target%:*}/${target#*:})
+            (cd repo && mkdocs build --dirty --site-dir ../public/${target%:*}/${target#*:}) ||  echo "Failed to build ${target}";continue
             echo ::endgroup::
-            echo ::endgroup::
-            $? && echo "::notice title=Build Sucessful::Branch '${target}' built successfully"
+            echo "::notice title=Build Sucessful::Branch '${target}' built successfully"
           done
           chmod -c -R +rX public/ | while read line; do
             echo "::info title=Invalid file permissions automatically fixed::$line"
