Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -47,30 +47,21 @@ jobs:
             mkdocs-cache-
           path: ./*
       - run: ls && ls public
-      - name: Checkout repository
-        # if: ${{ ! steps.cache-restore.outputs.cache-matched-key }}
-        uses: actions/checkout@v4
-        with:
-          path: repo
-          repository: ${{ env.PROD_REPO }}
-          fetch-depth: 0
       # - name: Set up Python runtime
       #   uses: actions/setup-python@v5
       #   with:
       #     python-version: ${{ env.PYTHON_VERSION }}
       #     cache: pip
       #     cache-dependency-path: requirements.txt
-      - name: Install Python dependencies
-        run: pip install -r repo/requirements.txt
       - run: ls && ls public
       - name: Create dev sub-deployments
         run: |
-          mkdir -p public
-          cd repo
-          git fetch
-          for pr in ${{ github.event.client_payload.pr-branches || inputs.pr-branches }}; do
-            git checkout -f origin/$pr || ( echo "Failed to checkout ${pr}"; continue )
-            mkdocs build --dirty --quiet --site-dir ../public/$pr
+          for target in ${{ github.event.client_payload.pr-branches || inputs.pr-branches }}; do
+            mkdir -vp repo && rm -vrf repo/* 
+            mkdir -vp "public/${target#*:}/${target%:*}"
+            echo "Repo:'${target%:*}'\nBranch:'${target#*:}'"
+            git clone --single-branch --branch ${target%:*} ${target#*:} repo || ( echo "Failed to checkout ${target}"; continue )
+            cd repo && mkdocs build --dirty --quiet --site-dir ../public/${target#*:}/${target%:*}
           done
           chmod -c -R +rX public/ | while read line; do
             echo "::info title=Invalid file permissions automatically fixed::$line"
@@ -80,8 +71,12 @@ jobs:
       - name: Make index.html
         run: |
           html="<h2>Currently Deployed Branches</h2><br><ul>"
-          for BRANCH in public/*/;do 
-            html="${html}<li><a href=\"${DEPLOY_URL}/$(basename ${BRANCH})\">$(stat -c %w ${BRANCH})</a> from <a href=\"https://github.com/${PROD_REPO}/pull/$(basename ${BRANCH})\">$(basename ${BRANCH})</a></li>"
+          for REPO in public/*;do
+            html="${html}<li>$REPO<ul>"
+            for BRANCH in public/$REPO/*;do
+              html="${html}<li><a href=\"${DEPLOY_URL}/${BRANCH}\">$(stat -c %w ${BRANCH})</a> from <a href=\"https://github.com/${REPO}/pull/${BRANCH}\">${BRANCH}</a></li>"
+            done
+            echo "${html}</ul></li>"
           done
           echo "${html}</ul>" > public/index.html
       - name: Upload to GitHub Pages
@@ -98,8 +93,8 @@ jobs:
           path: ./*
       - name: Print message
         run: |
-          for pr in ${{ github.event.client_payload.targets || inputs.targets }}; do                
-            echo "::notice title=Deployment Sucessful::Branch '${pr}' deployed to ${DEPLOY_URL}/${pr}"
+          for target in ${{ github.event.client_payload.targets || inputs.targets }}; do                
+            echo "::notice title=Deployment Sucessful::Branch '${target}' deployed to ${DEPLOY_URL}/${target#*:}/${target%:*}"
           done
       # - name: Post Cmment to PR
       #   run: |
