Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -29,7 +29,9 @@ jobs:
           echo "PR Branches: ${{ github.event.client_payload.pr-branches || inputs.pr-branches }}"
       - name: Fail
         if: ${{ ! ( github.event.client_payload.pr-branches || inputs.pr-branches ) }}
-        run: exit 1
+        run: |
+          echo "::error title=No Inputs::No input branches given. Nothing will be built."
+          exit 1
       - name: Checkout repository
         uses: actions/checkout@v4
         with:
