make more noise

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -49,20 +49,26 @@ jobs:
       - name: Create dev sub-deployments
         run: |
           for target in ${{ github.event.client_payload.targets || inputs.targets }}; do
+            echo "::group::Building for Repo:'${target%:*}' Branch:'${target#*:}"
+            echo "::group::Setting Up Directorys"
             rm -rf repo && mkdir -vp repo
-            mkdir -vp "public/${target%:*}/${target#*:}"
-            echo "Repo:'${target%:*}'"
-            echo "Branch:'${target#*:}'"
+            mkdir -vp "public/${target%:*}/${target#*:}"        
             echo "git clone --single-branch --branch ${target#*:} https://github.com/${target%:*} repo"
-            git clone --single-branch --branch ${target#*:} https://github.com/${target%:*} repo || ( echo "Failed to checkout ${target}"; continue )
+            git clone --single-branch --branch ${target#*:} https://github.com/${target%:*} repo ||  echo "Failed to checkout ${target}";continue
+            echo ::endgroup::
+            echo "::group::Installing Dependencies"
+            ls -latr repo
             (cd repo && pip install -r requirements.txt)
-            (cd repo && mkdocs build --dirty --quiet --site-dir ../public/${target%:*}/${target#*:})
+            echo ::endgroup::
+            echo "::group::Building"
+            (cd repo && mkdocs build --dirty --site-dir ../public/${target%:*}/${target#*:})
+            echo ::endgroup::
+            echo ::endgroup::
+            $? && echo "::notice title=Build Sucessful::Branch '${target}' built successfully"
           done
           chmod -c -R +rX public/ | while read line; do
             echo "::info title=Invalid file permissions automatically fixed::$line"
           done
-          cd ../
-      - run: ls && ls public
       - name: Make index.html
         run: |
           html="<h2>Currently Deployed Branches</h2><br><ul>"
